# Configuração de Deploy para Render
# https://render.com/docs/yaml-spec

services:
  # Serviço Web (Backend + Frontend)
  - type: web
    name: gerador-planos-aula
    runtime: node
    env: node
    region: oregon
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
